### ISSUE TITLE
nginx SupplementalGroups leak to worker process

### ISSUE THREAD

**Issue by jcoalson** [stephan13360/systemd-services#3]
It seems the reason for `SupplementalGroups=acme` is so that the TLS private keys can be owned and group-readably by `acme`, and read by the master nginx process. However I see that the worker process also inherits it. Doesn't that mean the worker process will also have access to the private keys?

```
# systemctl daemon-reload && systemctl start nginx
# ps -e -d -a -o pid,cmd,group,supgrp | grep nginx
  82479 nginx: master process /usr/ nginx    nginx,acme
  82480 nginx: worker process       nginx    nginx,acme
```

**Comment by AntonAttano** [comment]
I did not realize this until now, you are right.
But the worker process should always have access to the keys from the master process, because the worker process has to terminate the TLS connection. The master process is not involved in the TLS termination as far as I know.
So, as far as I can tell, this should be fine.

**Comment by jcoalson** [comment]
Ah right, thanks!
